name: Build DLL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Build DLL
      run: dotnet build Assets/CSChaCha20Unity/CSChaCha20Unity.csproj -c Release -o ./bin
