name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install coverlet global tool
      run: dotnet tool install --global coverlet.console

    - name: Run tests with code coverage
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        COVERAGE_FILE=coverage.cobertura.xml
        dotnet test Assets/CSChaCha20Unity/CSChaCha20Unity.csproj \
          --no-build \
          --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=cobertura \
          /p:CoverletOutput="$COVERAGE_FILE"

    - name: Upload coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CSharp -r coverage.cobertura.xml
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
