name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          2.1.x
          7.0.x
    - name: Test
      run: dotnet test tests/tests.csproj --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload coverage files
      env:
        CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CSharp $(find . -name 'coverage.cobertura.xml' -printf '-r %p ')
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
